spring.application.name=sentinel-security

spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelCore-secureOps
spring.datasource.username=postgres
spring.datasource.password=ram123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sentinelcore.ai.opencode.api-key=sk-754b2294c5915317-7ebc2d-dc96e0c5
sentinelcore.ai.opencode.model=56782247-f579-40a8-a5cc-6d0684ded134
sentinelcore.ai.opencode.endpoint=http://localhost:20128/v1/chat/completions

#logging.level.org.springframework.security=DEBUG